### ISSUE TITLE
fichier vfib

### ISSUE THREAD

**Issue by Eliah21** [benoit-tk/fibaro_thekeys#1]
le fichier vfib n'est pas au bon format. Quand on l'édite il y a plein de code HTML et ça ne ressemble en rien à du LUA (qui est au milieu mais mal encodé). Le fichier ne peut donc pas être importer dans le HC2 :

Operation could not be performed successfully and was interrupted. Error text:
Malformed vfib file

Il faut le réexporter depuis le HC2 et le remettre ici. 
Merci
----------
vfib file is malformed. You need to export it from HC2 and put it here again. thanks

**Comment by benoit-tk** [comment]
Le fichier vfib est un json. Il etait effectivement invalide. 
C'est corrigé.
